account_ids:
  - 237763167690

# If aws_region is not specified, the script will look at all regions
aws_regions:
  - us-east-1
  - us-east-2

controller:
  ip: x.x.x.x
  username: admin

defaults:
  role_name: aviatrix-role-app
  managed_tgw: True
  avtx_transit: True
  spoke_gw_size: t3.medium
  hpe: True
  gw_zones: ["a","b"]
  add_vpc_cidr: False